[sessions]
api_hash = "dce44a898d0d7330000d7f78cb9115d6"
api_id = 10151151

[flood]

messages = [ "Пошел нахуй", "админ шалава", "мать админа шлюха", "Привет от @AstroForexExperts20",  "Хрю хрю хрю", "А вы знали что мама админа патаскуха кароче", "💸 Спонсор: Лучший киви бот @CloudQ1w1Bot", "Лучший шоп в тг - @CloudShopV3RoBot", "Рот свой будешь открывать у стоматолога!", "Самолет крутился как твоя мать", "твой анус на моем хуе, как батон будет крошится, уебище ебанное, рой себе убежище, потому что мой хуй устроит в твоём рту апокалипсис", "ты понимаешь, что я тебе сейчас буду ебало сносить хуес, как построение старое", "слышь кочерга ебанная, я тебе сейчас анал буду чистить салим хуем, от всяких металлов", "ты понимаешь, что ты лохушка ебанная, которая медленно пишет, потому что ему член мой в жопе мешает", "ты понимаешь, что ты с горя пьёшь мою сперму вместо водки  я тебе на похороны ещё могу своей мочи дать запить"]
delay = [ 1,]
messages_count = 0
trigger = "777"
